spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYDATA_DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update